export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_FULLFILLED = 'GET_COMMENTS_FULLFILLED';
export const ADD_COMMENT_PENDING = 'ADD_COMMENT_PENDING';
export const ADD_COMMENT_FULLFILLED = 'ADD_COMMENT_FULLFILLED';
export const HIDE_LOADER = 'HIDE_LOADER';
